package.json

After adding *svg.js* as a dependency
```
$ npm install svg.js --save                                                                                                                        
svg.js@1.0.1 node_modules/svg.js
```
when I update deps I get a warning
```
$ npm install
npm WARN package.json svg.js@1.0.1 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
svg.js@1.0.1 node_modules/svg.js
```

Fixed npm warning about "repositories" property

---

README.md

Hey there. I may be misunderstanding, so feel free to dismiss this, but the `merge` method example for `BBox` wasn't working. I looked at the source for a few minutes, and realized that the first two lines in the example were missing a call to `bbox`, since `merge` belongs to `BBox` instances, not `Rect` instances.
Thanks for making such a great lib. Really enjoying it so far :sparkles:

Added missing `.bbox()` calls to merge example

---

src/sugar.js

The real problem is that when the `sugar.js` function `radius()` is called on the result of `animate()`, it [calls `SVG.FX.rx()`](https://github.com/wout/svg.js/blob/master/src/sugar.js#L81), which actually resolves to [this function](https://github.com/wout/svg.js/blob/master/src/ellipse.js#L44) and not the [intended one](https://github.com/wout/svg.js/blob/master/src/ellipse.js#L17). I appreciate there may be a better way of solving this; I'm not that familiar with javascript.
The only real changes are lines 79-81. My git and/or editor seems to have messed with the whitespace, too, so I have _deliberately_ not yet updated `/dist/svg.[min.]js` for that reason (i.e. the diff is confusing).

Fixes #366

---

README.md

I see what you mean about the issue of user coordinates being more general than the way I initially identified it.
However, in order to make a sensible place to put the warning I wanted to add, I needed to reorganize some of the documentation sections. 
I have replaced the 'Manipulating elements', 'Attribute references', and 'Inserting elements' sections with 4 new sections:
* Attributes and styles
* Classes
* Transforming elements
* Altering the element tree
I have moved the method descriptions around as follows:
In 'Attributes and styles':
* `attr, style, reference, hide, show, visible`
In 'Classes':
* `classes, hasClass, addClass, removeClass, toggleClass`
In 'Transforming elements':
* `transform, size, width, height, move, x, y, center, cx, cy, dmove, dx, dy`
In 'Altering the element …

Reorganize and clarify documentation

---

src/regex.js

Description of necessary functionality for a regex that matches Javascript numbers found in Eloquent Javascript, (Ch 9, last exercise). See: http://eloquentjavascript.net/09_regexp.html#h_izldJoT3uv
Probably solves issue #438.

Fix regex for isNumber

---

src/element.js

I've encountered situation where SVG.adopt (line 176) returns null, which leads to `Uncaught TypeError: Cannot read property 'node' of null`. Checking whether parent exists fixes it.

Uncaught TypeError: Cannot read property 'node' of null

---

src/boxes.js

The document object in IE does not have the contains function  as a method.  This can cause a stack overflow as you can get stuck in an endless try catch loop.   document.body.contains will work in IE, Firefox, and Chrome and will resolve this issue.

Changed document.contains to document.body.contains

---

src/transform.js

When you use 'move' animation of the group element, and use transformation for only one coordinate (x or y) then it's resets other coordinate to 0. 
For example if your group is on coordinate 100, 100 and you call animate y(500), it goes to 0, 500.
This is caused because undo is made for both coordinates.

Fix groups animation

---

src/fx.js

In this case the String.at() polyflll interferes with the check for `el.at`, resulting in animations trying to animate attributes not existing like "o" in case of "opacity"

Fix broken animations, if using polyfills for es6/7 proposals 

---

src/fx.js

This fixed the a.undo is not a function error. The for loop was going down into  the array's prototype chain.

Fix going down prototype chain

---

svg.js.d.ts

- Edit export as recommended in typescript [templates](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) and [lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/index.d.ts#L239) and [angular](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/angular/index.d.ts#L17) typings.
- Add `Matrix` property
Fix for #564

Add UMD module support Add Matrix property

---

CHANGELOG.md

The document [“Keep A CHANGELOG”](http://keepachangelog.com) describes some sensible guidelines for formatting changelog notes.  I think the guidelines make changelogs much more useful and human-friendly.

Format change log according to “Keep a CHANGELOG” guidelines

---

spec/spec/fx.js
src/fx.js
src/textpath.js

While writing the zoom plugin I discovered, that the fx module didnt cover a usecase which was orginally intended to work. You cant pass multilple parameter to methods when animating them.
"Stop", I hear you saying, "`move()` _does_ expect 2 parameters!". Well yes thats true but the implementation of `move()` breaks it down to `x()` and `y()` which both only take one parameter.
So this wasnt possible: `el.animate().zoom(level, point)`.
This PR aims to fix this while adding the possibility to use `static` values which stay the same while animating. In this case: `point`. When you animate zooming you dont want the point to which you zoom to be animated. It stays the same.
So fx now does the following:
- you set `el.animate().method(val1, val2)`
- if `el.method()` returns the same number of …

Adds the intended functionality to call animate functions with multiple parameter

---

svg.js.d.ts

Updated:
* `.attr()` getter method is missing in `Element` and `Animation` 
* `.leading()` getter method is missing in `Text`
* `.lines()` getter method in `Text` is actually return a `Set` of `Tspan`
* `.radius(x: number, y?: number)` method is missing in `Rect`
* `FontData` can accept `size` and `leading` property as `NumberAlias`

Add missing type definitions to svg.js.d.ts

---

spec/spec/fx.js
src/fx.js

Adding animation capabilities for width() and height() setters. (Indicated as currently animatable in documentation). Unit tests included.
Refers to #675 
To be reviewed as I'm not 100% sure about my code !

Make width() and height() setters animatable

---

src/doc.js
svg.js.d.ts

Hi, thanks for this awesome lib :) 
The default TypeScript declaration file gave me a few syntax errors when I tried to use it. These are the fixes that made it work for me. I have never used TS before, so this is more or less the result of "hacking by error message", but the changes are fairly simple syntax fixes.
For some of the stuff I touched, at least in the Transformation interface, I'm not sure the declaration exactly matches all use cases of the JS function even now. But I don't know enough about TS or svg.js to be certain.
Going through function definitions, I also found the function spof() in doc.js which had an unused parameter spof (whose type was undeclared in the declaration, hence a syntax error). I removed the parameter.

TypeScript fixes and remove unused parameter

---

svg.js.d.ts

This adds the getter form of the `svg` method to the TypeScript definitions.

Add getter form of svg method to TypeScript definition

---

svg.js.d.ts

I can't use array like `[[0, 235], [245, 123], [521, 34]]` as array of points. This fix makes it possible to use `ArrayPoint[]` in with plot method in TS.
Thank you.

Fix typings for arrays that takes plot method.

---

svg.js.d.ts

I am using this library in TypeScript.
In my case, first parameter was recognized as an Object.
```
import * as SVG from 'svg.js';
...
const items = this.polyline.remember('polygonCircle') as any as SVG.Element[];
```
Definition order changed
```
import * as SVG from 'svg.js';
...
const items = this.polyline.remember('polygonCircle') as SVG.Element[];
```
In TypeScript, method order is very important.
https://www.typescriptlang.org/docs/handbook/declaration-merging.html
Thanks

Fix typings for memory.js remember method order

---

CHANGELOG.md
spec/spec/event.js
src/element.js
src/event.js
src/svg.js

This PR is Work in Progress.
It moves the event handlers on the node as discussed in #807. It also changes #550 so that we now have `fire()` and `dispatch()` as two seperate methods.
Furthermore its now possible to remove multiple elements at once when calling `SVG.off()`. (Binding was already possible). It also adds the option argument to `SVG.off()` which is needed there.
I made this PR to see which changes are required to make the proposal work. Its not that much overhead to manage HTMLNodes.
Comments are welcome!

proposal for #807, includes #550, `SVG.off()` multiple events and option argument

---

src/flatten.js

In #826 I talked about having flatten and ungroup as methods. This PR i sthe implementation. 
Ungroup breaks up groups and nested svgs like when you would ungroup elements in photoshop.
Flatten just makes the whole svg structure flat.

make ungroup working on groups and nested for one depths

---

src/svg.js

This PR addresses the discussion in issue #767 - Bundling issues when using webpack and the `this` reference that was hardcoded.

Add global reference to support 'window' in bundlers - fixes #767

---

svg.js.d.ts

As discussed with @Fuzzyma in issue 597, I added some typescript declarations. Not really sure about `finish()`, `pause()`, `play()` or `reverse(reversed?: boolean)` in `interface Animation`, as it must be for a reason they're not there.
In `interface Transformation` I added `scale?: number;` to use something like `svgdoc.select("#line").get(0).animate(500, "<>").transform({scale:2}, true);` without getting syntax errors in vscode.

Added declarations to Transformation and Animation interfaces

---

CHANGELOG.md
dist/svg.js
src/elements/A.js
src/elements/Bare.js
src/elements/Circle.js
src/elements/ClipPath.js
src/elements/Doc.js
src/elements/Ellipse.js
src/elements/G.js
src/elements/Gradient.js
src/elements/Image.js
src/elements/Line.js
src/elements/Marker.js
src/elements/Mask.js
src/elements/Path.js
src/elements/Pattern.js
src/elements/Polygon.js
src/elements/Polyline.js
src/elements/Rect.js
src/elements/Style.js
src/elements/Symbol.js
src/elements/Text.js
src/elements/TextPath.js
src/elements/Tspan.js
src/elements/Use.js
src/utils/adopter.js

e.g.
- `canvas.rect({x:100})` or
- `canvas.rect(100, 100, {x:100})`
Please add your thoughts!
Iam not entirely satisfied with the way I need to wrap every function on every export. However, it was the cleanest way for now

added possibility to pass in additional attribues to element creators (#796)

---

src/doc.js
src/element.js

It solves the `node.getAttribute is not a function` issue in Shadow DOM.

Add node document-fragment type check

---

spec/spec/pointarray.js
src/types/PointArray.js

I recently had occasion to want to transform the points in an `SVG.Polygon` according to a transformation matrix.  (The motivation is to "inline" `transform` attributes into the point coordinates themselves, for software that supports SVG but not the `transform` attribute.)  `SVG.Polygon.array` reveals the `SVG.PointArray` that represents the coordinates, and `SVG.Polygon.plot` lets me put a transformed `PointArray` back into the polygon.  What's missing is an `SVG.PointArray.transform` (essentially a loop over `SVG.Point.transform`) to transform the `PointArray` according to a given matrix.
This PR adds this functionality.  If you like the proposed addition in principle, I can write tests and documentation.

Add PointArray.transform by analogy to Point.transform

---

.config/rollup.config.js
package.json
svg.js.d.ts

I attempted to use 3.0.11 with TypeScript. I think the rollup.conf.js file has the wrong format after your changes to use esm modules. Using 'umd' allows it to be imported correctly.
I also updated some of the obvious changes to the .d.ts from the changelog. I have to confess my changes are not complete, but they allowed me to use 3.0.11 in my application.

use umd format in rollup. Update .d.ts file with changes for 3.0

---

svg.js.d.ts

Added missing key/value overload for 'text.font()'

---

spec/spec/path.js
src/types/PathArray.js

@Fuzzyma Since there are paths that have 0 width/height (i.e. straight line) the original code was generating invalid path data. This fixes this issue.

Fixed path transformation when box width or height is 0

---

svg.js.d.ts

Fixing event binding method in Element and parse method in PathArray class.
Fix https://github.com/svgdotjs/svg.js/issues/1002 and https://github.com/svgdotjs/svg.js/issues/995.

Typescript definition file cleaning

---

svg.js.d.ts

I found missing function definitions.
https://github.com/svgdotjs/svg.js/blob/master/src/modules/optional/sugar.js#L167-L168

Add mouseenter()/mouseleave() function definition to types.

---

svg.js.d.ts

The ease method on the runner takes the same constructor strings as the Ease class, so you can do things like element.animate(1000).ease('-').rotate(360).loop() 
Currently typescript throws an error saying that ease only accepts a Function as an argument.

Add optional string type to Runner.ease

---

svg.js.d.ts

CSSStyleDeclaration contains readonly rule, so I excluded them, otherwise it doesn't make sense
I didn't touch the Runner `css()` because I don't know the exact behavior of it.

Better typing for css getter/setter

---

svg.js.d.ts

Fixes typescript errors List and ForeignObject introduced in #1123 and hopefully with same line separators.

Fix types for List and ForeignObject (same line separators)

---

svg.js.d.ts

We need this to be able to pass strings like "top-right" or "center" as transform origin on TypeScript, as they're already supported on JavaScript.
@neomorfeo

Allow strings to be passed as transform origin on TS

---

spec/spec/utils/pathParser.js
src/utils/pathParser.js

This PR proposes a fix for parsing Elliptical Arc commands in SVG paths. The parser has been failing to parse some valid arc commands. For example, the [grammar](https://www.w3.org/TR/SVG/paths.html#PathDataBNF) allows for whitespace/comma to be omitted following one of the arc flags.

fix arc flags parsing

---

svg.js.d.ts

This can be a breaking change. But it will also fix the contract of the method.

findOne can return null

---

svg.js.d.ts

Current typings for `Runner` do not include the `dmove` method defined [here](https://github.com/svgdotjs/svg.js/blob/master/src/animation/Runner.js#L885). This PR adds that definition.
Created #1232 for this PR.

Adds dmove to type definition for class Runner

---

src/types/Point.js

The Point instance is already created, so don't create a new one.
Edit: also don't clone the newly created Matrix from `getScreenCTM`

Performance: don't create a double clone in point

---

.config/rollup.config.js
spec/spec/elements/Dom.js
src/elements/Dom.js
svg.js.d.ts

This PR is related to https://github.com/svgdotjs/svg.js/issues/1160 .
Currently, `Dom.clone()` (so `Svg.clone()`, `Container.clone()`...) assigns new IDs to cloned elements. This is usually what the user expects, since *not* assigning new IDs could lead to unexpected, hard-to-track behaviors. For example, if clones are transformed independently and displayed together, they might "share" some properties due to IDs clash.
However, when the user knows what he does, not assigning new IDs on clone can be an easy workaround to https://github.com/svgdotjs/svg.js/issues/1160 . This is because `Dom.clone()` does not update all references (eg. `fill="url(#someId)"`) when assigning new IDs.
This PR introduces a new boolean optional parameter `assignNewIds` to `Dom.clone()`:
- `true` (default): No …

Clone without assigning new IDs

---

spec/spec/animation/Runner.js
src/animation/Runner.js
src/animation/Timeline.js

There are small typos in:
- spec/spec/animation/Runner.js
- src/animation/Runner.js
- src/animation/Timeline.js
Fixes:
- Should read `successful` rather than `successfull`.
- Should read `transforms` rather than `tranforms`.
- Should read `resetting` rather than `reseting`.
- Should read `overwrite` rather than `overwfrite`.
- Should read `morpher` rather than `morepher`.
- Should read `declarative` rather than `declaritive`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

svg.js.d.ts

this pr is to fix issue #1307 .

fix: add Fragment declaration in svg.js.d.ts

---

spec/spec/types/List.js
src/types/List.js

Allow access to original Array.prototype methods on List prefixed with $

---

svg.js.d.ts

shape.css({
backgroundColor:'red'   // ts success, but style set inoperative
})
shape.css({
'background-color':'red'   // ts error, but style set success
})
this request fix typescript type  CSSStyleDeclaration

fix: shape.css() typescript tip

---

svg.js.d.ts

The method has not existed since c37d94a.

Remove gbox() from G in svg.js.d.ts
