README.md

We developed and open-sourced at @jillix a svg.js library for connecting SVG elements. Hope you enjoy!

Added connectable plugin.

---

README.md

Added comic.js to plugins section in README.md

---

README.md

Added a link to https://github.com/loredanacirstea/svg.connectable.js. 
See http://jsfiddle.net/loredana_cirstea/L2sjjc3b/10/ for a demo.

added link to svg.connectable.js fork

---

package.json
svg.js.d.ts

seeing as typescript is starting to get more popular.
and with angular2 in beta, i thought it would be a good time to write the typescript definitions for this library.
i dont own all the credit for the definitions, i started with the definitions i found on http://definitelytyped.org/ and expanded on that. [here is the original](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/svgjs/svgjs.d.ts)
anyways feel free to review / change it since im sure i miss a few things :D
also i did not write the definitions for SVG.FX and the animations in general, i ran out of time :D

added svg.js.d.ts

---

spec/spec/fx.js

I have found this error while adding tests for the FX module. I also added two call to animate just to make sure that the situations array gets filled.

Fix the test of SVG.FX.afterAll

---

README.md

@Fuzzyma & @RmiTtro can you review my changes before I merge it into master?

fix wrong doc for local testing

---

dist/svg.js
src/boxes.js

Changed "bitch" in comment to "pain" to avoid profanity checks (required before releasing code) when embedding this code into other projects.

Comment updated to pain

---

src/element.js

Correctly handle namespaced self-closing tags

---

svg.js.d.ts

I found missing methods(parent(), doc()) for Element
Thanks

Fix typings for missing element.js method

---

svg.js.d.ts

Or should I not access these directly?

Typescript: X & Y Properties on Point

---

svg.js.d.ts

Sorry, I found more errors in the d.ts file when I tried to use it.

cleanup of d.ts

---

svg.js.d.ts

Added missing 'clone(parent)' overload to .d.ts file

---

svg.js.d.ts

Fix typo in type file for Polyline and Marker

---

svg.js.d.ts

Updated animate method to accept a custom ease function as per the docs (https://svgjs.com/docs/2.7/animating/#easing)

Updated ease type in svg.js.d.ts

---

svg.js.d.ts

Update typescript definition to align with Javascript API.

Update typescript definition file.

---

spec/SpecRunner.html
spec/spec/timeline.js
src/animation/Timeline.js

In Timeline.getEndTimeOfTimeline() I check weather runnerInfo is truthy: 
var duration = runnerInfo ? runnerInfo.runner.duration() : 0
var startTime = runnerInfo ? runnerInfo.start : 0
I'm not sure weather this is required; this might be enough:
var duration = runnerInfo.runner.duration()
var startTime =runnerInfo.start
I do these checks because they are done in Timeline.getEndTime()

bugfix for issue #964

---

package-lock.json
src/modules/core/parser.js

**Note:** 
- this will resolve #1023 
- I considered writing a test for the fix, but could not find an easy 
example to adapt. Since it's a low impact change, I decided against adding one.

#1023 - hide parser from screen readers

---

svg.js.d.ts

Fixes Element.animate typing

---

package-lock.json
src/main.js
svg.js.d.ts

Added `getWindow`, `restoreWindow`, `saveWindow`, and `withWindow` to the exports of "main.js" and to the type declarations in "svg.js.d.ts".

Added exports from window.js

---

svg.js.d.ts

We need this to be able to define styles on the SVG from TypeScript.
@neomorfeo

Add style() to Container on TS bindings

---

svg.js.d.ts

Types for Style

---

svg.js.d.ts

Add zoom():number to d.ts to get current zoom level

Update svg.js.d.ts -> zoom

---

spec/spec/types/EventTarget.js
src/types/EventTarget.js
svg.js.d.ts

Add parameter "options" to EventTarget.off()

---

svg.js.d.ts

Added Timeline.active() for Typescript
https://github.com/svgdotjs/svg.js/blob/master/src/animation/Timeline.js#L47

d.ts Timeline.active()

---

svg.js.d.ts

fix: Add second parameter definition
